### PR TITLE
Fix issue in Arrays::getNestedValue

### PR DESCRIPTION
**Pull request by DarioSwain**
Fix Arrays::getNestedValue in case when keys lead to non-existing element with scalar parent.

### CODE REVIEW

**Comment by DarioSwain** [comment]
Hi @woru @Danon, could you please take a look on this PR? Thanks!

**Comment by Danon** [comment]
Hey, thanks for the PR :)

Could you please illustrate what was the outcome of `getNestedValueShouldReturnNullWhenZeroKeyNotFound()`? Can't run it right now ;) 

Two questions:
 - Is `'0'` a special value, or will the test also fail for `'1'`?
 - Could you remove `var_dump() ` from test?

**Comment by DarioSwain** [comment]
Hi @Danon, 
Sorry, missed this var_dump 😄

Before this fix getNestedValue returned: "value". 
Due to self::toArray($array) which is wrapping any scalar value into array, and answer for you first question is: it's only for '0', because `self::toArray('value') => ['value']` and in this case 0 key is exists, but all other keys will returns null on self::getValue.

I've updated PR. Thank you for quick response!

**Comment by Danon** [comment]
I suppose a simmilar bug could be recreated with these lines?

 - `Arrays::getNestedValue($array, ['1', '2', '3', 0]);`
 - `Arrays::getNestedValue($array, ['1', '2', '3', '0', '0']); // don't think so`

Maybe you could try those, and if they do recreate the bug, see if your fix also fixes them? If they don't illustrate the bug as your finding then ignore them :)

Ps: how do you like using ozuo so far? ;)

**Comment by Danon** [comment]
Also, @DarioSwain please make sure the bug doesn't occur in `Arrays::hasNestedKey()` and `Arrays::removeNestedKey()`.

**Comment by DarioSwain** [comment]
@Danon yes, for both your examples will be returned "value" instead of null. My fix is also tackle them, I've added few tests to cover those cases.

Regarding hasNestedKey() and removeNestedKey(), you're right, them also do not handle non-existing keys properly, I've added few checks in my latest commit (+ tests).

> Ps: how do you like using ozuo so far? ;)
I'm just experimenting with ouzo-goodies, can't say anything regarding framework itself.

**Comment by Danon** [comment]
Thanks a lot!! 

> @Danon yes, for both your examples will be returned "value" instead of null. My fix is also tackle them, I've added few tests to cover those cases.

Are you sure all your new tests fail, if your fix is not applied? :) Just checking. 

> Regarding hasNestedKey() and removeNestedKey(), you're right, them also do not handle non-existing keys properly, I've added few checks in my latest commit (+ tests).

Ok, thanks :)

One additional, case in my mind. What's the resulting array from
```php
Arrays::setNestedValue($array, ['1', '2', '3', 0], "new value");
```
Can you also check this method for me? That's the last one, I promise :)

**Comment by Danon** [comment]
> > Ps: how do you like using ozuo so far? ;)
> 
> I'm just experimenting with ouzo-goodies, can't say anything regarding framework itself.

Oku, how do you like Ouzo Goodies? :D

**Comment by DarioSwain** [comment]
> Are you sure all your new tests fail, if your fix is not applied? :) Just checking.

Yes.
image

> Arrays::setNestedValue($array, ['1', '2', '3', 0], "new value");

This case is working fine, it returns: ['1' => ['2' => ['3' => [ 0 => 'new value']]]]

> Oku, how do you like Ouzo Goodies? :D

I like it, a lot of useful tools which you haven't to redevelop from scratch, great work 👍

**Comment by Danon** [comment]
> > Are you sure all your new tests fail, if your fix is not applied? :) Just checking.
> 
> Yes.

Ok, thank you for that double check :) 

> > Arrays::setNestedValue($array, ['1', '2', '3', 0], "new value");
> 
> This case is working fine, it returns: ['1' => ['2' => ['3' => [ 0 => 'new value']]]]

Great we got that out of our way :) 

Ok, now we only need to ask @bbankowski @piotrooo @andrzejo for a review. We'll probably have to wait through the weekend.

**Comment by bbankowski** [comment]
@DarioSwain kudos for the fix, it looks good! I've just merged it into master. It will go with the next release, which we will hopefully do very soon :)

@Danon thanks for the review.

**Pull request merged**
